name: "(T3K) T3000 profiler tests"

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 */8 * * *" # This cron schedule runs the workflow every 8 hours

jobs:
  build-artifact-profiler:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      arch: '["wormhole_b0"]'
      tracy: true
    secrets: inherit
  t3000-profiler-tests:
    needs: build-artifact-profiler
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          {
            name: "T3000 profiler tests",
            arch: wormhole_b0,
            runs-on: [arch-wormhole_b0, "config-t3000", "in-service", "pipeline-perf"],
            cmd: './tests/scripts/run_profiler_regressions.sh'
          },
        ]
    name: ${{ matrix.test-group.name }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.test-group.arch }}
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    environment: dev
    runs-on: ${{ matrix.test-group.runs-on }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: TTMetal_build_${{ matrix.test-group.arch }}_profiler
      - name: Extract files
        run: tar -xvf ttm_${{ matrix.test-group.arch }}.tar
      - uses: ./.github/actions/install-python-deps
      - name: Run profiler regression tests
        timeout-minutes: 30
        run: |
          ./tests/scripts/run_profiler_regressions.sh
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: U03BJ1L3LUQ # Mo Memarian
